#!/bin/bash 
#SBATCH --partition=short-serial 
#SBATCH --job-name=myRarray
#SBATCH -o %A_%a.out
#SBATCH -e %A_%a.err
#SBATCH --time=240:00
#SBATCH --array=0-30

stepsize=40
module load jaspy
source ../environments/EE_venv/bin/activate
python EE_download_timeseries.py -s MODIS/Germany/satdata$((${SLURM_ARRAY_TASK_ID}*$stepsize)) -start $((${SLURM_ARRAY_TASK_ID}*$stepsize)) -end $(($((${SLURM_ARRAY_TASK_ID}*$stepsize))+$stepsize))